include::header.adoc[]
//override default to include table css
:stylesheet: front.css
:leveloffset: -1

:course: CS 113
:title: Computer Science I
:term: Spring 2021

= {course}: {title} -- {term}

[.anns]
== Announcements
* link:asst04.html[Assignment 4] is due on March 19 
* Topic this week: link:#functions1[Functions]
* We will have a code jam in lab this week! Check out the link:jam2Guide.html[Jam 2 Study Guide] for details!

== **Schedule**

The syllabus may change during the semester. Please check here every week for updates 
on lecture content, worksheets, and assignments.

include::schedule.adoc[]

== Course Info

**Welcome to CS113**, an introduction to computer science. This class covers 
the basics of computer programming using Java. Students will learn 
fundamental programming concepts, such as variables, conditional statements, 
loops, functions, and classes. Students will develop their ability to write 
programs to solve a variety of problems, read existing programs, 
and find and fix errors in existing code. 

No prior computer programming experience is necessary or expected for this
class. If you have never programmed, or don't know much about computers, this
class is for YOU! However, we do ask students to have "quantitative readiness
(QA)". In this course, QA means a willingness to confront equations and
concepts with curiosity. Students may need to do additional learning outside
of class if they encounter mathematical concepts to which they do not have
previous exposure.

Computer programmers must mix systematic thinking with creativity. Programming 
can be time-consuming and difficult work, but the results are rewarding!  

_This course is appropriate for all students who want to learn how to read, write, 
and debug computer programs as well as learn solve problems like a computer scientist_. 

=== Meeting Times

[.center,options="header,autowidth"]
|===
| Activity | Location | Time

| Lecture | Zoom (Link posted on Slack) | Tuesday, Friday, 11:10am-12:30pm EST
| Lab A | Zoom | Tuesday, 12:40pm-2pm EST
| Lab B | Zoom | Friday, 10:10am-11:00am EST
| Office Hours | By appointment | See calend.ly link on Slack

|===

=== TA Office Hours

All TA office hours will be on Zoom. See our course slack for details!

[.center,options="header,autowidth"]
|===
| Day | Morning | 6-8pm | 7-9pm | 8-10pm 

| Sun | | | | Yuxiao 
| Mon | | | Al |
| Tues | |Angie | Sarah | 
| Weds | Angie (9-11am) | | Sarah | 
| Thurs | | | Al | Yuxiao
| Fri | | | |

|===

== Text and Software

*  **Introduction to Programming in Java (Second Edition)** by Robert Sedgewick & Kevin Wayne. Addison-Wesley 2017. Available in Campus Bookstore, or purchase online from Amazon.com (Price on August 19, 2020 is $35.99 for e-text, $65.00 paperback). Book's companion website: Click here.
*  **Dropbox Account** Please go to link:https://dropbox.com/[dropbox.com] and register. You will be using dropbox to submit assignments. 
*  **Slack** Please go to link:https://slack.com/signin[slack.com]. Our workspace is BrynMawr-CS110-F20. You can ask questions and request one-on-one help over zoom using this course's slack channel. 
*  **Development environment** This refers to the tools we will use to write and run code. We will distribute an installer to help you set this up. We will use git bash, OpenJDK-11, and Visual Studio Code (VS Code).

*Resources*

* link:develEnvSetup.html[Instructions for setting up Java]
* link:https://github.com/BrynMawr-CS113-S2021/code-examples[JAVA programs from lecture]

== Grading Policies

All graded work will receive a grade, 4.0, 3.7, 3.3, 3.0, 2.7, 2.3, 2.0, 1.7,
1.3, 1.0, or 0.0. At the end of the semester, final grades will be calculated
as a weighted average of all grades according to the following weights:

|===
| 20% | Final Exam
| 15% | Midterm
| 35% | Assignments
| 15% | Code jams
| 15% | Presentations
|===

//include::quizzes.adoc[]

//include::labPolicy.adoc[]

include::latePolicy.adoc[]

include::integrity.adoc[]

include::accomodations.adoc[]

== External Links

Links that are related to the course may be posted here. If you have suggestions for links, let us know.

[unstyled]
 * link:http://www.dropbox.com/[Dropbox]
 * link:https://www.brynmawr.edu/academicsupport/academic-and-student-support-services[Academic Support, including help with math and quantitative skills!]
 * This site was generated with link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[asciidoctor]
