include::header.adoc[]

:title: Jam 2: Study Guide
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1

= {title}

Jams are open book. 40 minutes in lab.

Topics:

This quiz includes the previous topics from Jam 1 plus
* Conditional statements: `if`/`else`
* Logical and relational operators: `&&`, `||`, `!`, `<=`, `>=`, `>`, `<` , `==`
* Arithmetic operators: `+`, `-`, `*`, `/`, `++`, `--`, `+=` , `-=`, `*=`, `/=`
* Accumulator variable pattern
* String comparisons, the empty string: `""`

Write Java programs to check your answers. Or you can ask a TA or instructor 
to give feedback on your responses.

= Practice questions

1) What is the **value** and **type** for each of the following
expressions? 

- `2 + 3`
- `2*3.0`
- `2.0 + 3`
- `6/10`
- `6/10.0`
- `5 - 2 * 3`
- `"12"`
- `2.0`
- `2+4*2+1`
- `"I love " + "CS"`

2) Given the following variables, what is the **value** and **type** for each of the following expressions? 

[source,java]
----
int x = 5;
int y = 13;
String message = "cat!";
boolean Done = false;
----

** `x < 10 && y < 10`
** `x < 10 || y < 10`
** `x < 10 && x > 0`
** `x > 10 || x < 0`
** `(5/x) > 7.0`
** `message.compareTo("cats") == 0`
** `!Done`
** `Done || (x < 6 && y > 10)`

8) Consider the following code 

[source,java]
----
String colorName = "purple";

if (colorName.compareTo("red") != 0) {
  System.out.println(colorName + " is not primary");
}
else if (colorName.compareTo("blue") != 0 {
  System.out.println(colorName + " is not primary");
}
else if (colorName.compareTo("yellow") != 0) {
  System.out.println(colorName + " is not primary");
}
else {
  System.out.println(colorName + " is primary");
}
----

* Draw a decision diagram corresponding to this if statement.
* What does the above code print when 
** `colorName = "purple"`? 
** `colorName = "red"`?
** `colorName = "yellow"`? 
