include::header.adoc[]

:title: Jam 3: Study Guide
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1

= {title}

Jams are open book. 40 minutes in lab.

Topics:

This quiz includes the previous topics from Jam 1-2 plus

* loops: for- and while-
* `sin` and `cos`
* functions: defining and calling, return types, return statements, parameters (aka arguments)
* scope of a variable

= Practice questions

4) Write a function that inputs a month as an integer and returns a string name for that month. For example, 
if we call the function with the number 1, the function should return "January". Call your function from setup() for each month of the year (use a loop) and print the results to the console.

5) Consider the following loop

[source,java]
----
int pinLength = 4;
String pin = "";
for (int i = 0; i < pinLength; i++) {
  pin = pin + "*";
  System.out.println(pin);
}
System.out.println("Enter your pin: "+pin);
----

* What is output to the console when we run this program?
* Convert the loop above so it uses a while loop instead of a for loop

7) Consider the following program

[source,java]
----
class Mystery {
  public static String mystery2(String message, String symbol) {
    message = symbol+message+symbol;
    // (a) Show function stack here
    return message;
  }

  public static void mystery1(String message) {
    System.out.println(message);
    message = mystery2(message, "~~");
    System.out.println(message);
    // (b) Show function stack here
  }

  public static void main(String[] args) {
    String userText = "Happy Halloween!";
    mystery1(userText);
    System.out.println(userText);
  }
}
----

* Show the function stack starting at `setup()` and ending with the comment labeled (a).
* Show the function stack starting at `setup()` and ending with the comment labeled (b).
* What global variables are used by this program?
* What are the parameters to mystery1?
* What variables are in scope in setup?
* What variables are in scope in function mystery1?
* What variables are in scope in mystery2?
* What is the console output of this program?
* What text is drawn to the canvas?
