include::header.adoc[]

:title: Jam 4: Study Guide
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1

= {title}

Jams are open book. 40 minutes in lab.

Topics:

This quiz includes the previous topics from Jams 1, 2 and 3 plus

* arrays
* classes
** defining and using classes
** terms: methods, member variables, accessors (getters), mutators (setters) 
** scope of member variables

General quiz self-assessment: 

* Can you define terms? 
* Are you familiar with the Processing functions we use in class and labs?
* Do you know the syntax for defining and using variables, if statements, loops, functions, and classes?
* Can you read and understand code? Could you spot errors? Can you trace the execution and deduce the values for all variables?
* Can you write code which solves a given problem? Can you solve it in different ways? For example, if a question asks you to use a function, can you solve the problem using a function?

= Practice questions

1) Loop practice. Can you write loops in `main` which produce the following console output?

* Write a loop that prints the following sequence to the console
[source,java]
----
The next number is:  -5
The next number is:  -4
The next number is:  -3
The next number is:  -2
The next number is:  -1
The next number is:  0
The next number is:  1
The next number is:  2
The next number is:  3
The next number is:  4
The next number is:  5
----

* Write a loop that prints the following sequence to the console

[source,java]
----
X =  10.0
X =  20.0
X =  30.0
X =  40.0
X =  50.0
X =  60.0
X =  70.0
X =  80.0
X =  90.0
----

* Write a program that outputs the following to the console

[source,java]
----
10
9
8
7
6
5
4
3
2
1
Blast off!
----

* Write a program that outputs the following pattern to the console

[source,java]
----
*
**
***
****
*****
----

* Write a program that outputs a 5x5 square of asterisk to the console

[source,java]
----
*****
*****
*****
*****
*****
----

2) Loop practice. Use loops to compute quantities over random numbers.

* Using a loop, compute the sum of 5 random numbers between -10 and 10. Output the results to the console. 
Below is an example

[source,java]
----
9.732847
3.099474
-9.973539
2.9620247
-6.101103
Sum: -0.28029633
----

* Using a loop, compute the maximum value of 5 random numbers between -10 and 10.

3) Function practice. Write functions corresponding to the following specifications.
For each question, test your function from `main` using an array of random values 
as input.  Your function should not hard-code the length of the array. You should also 
print the result to the console.

* Write a function that converts miles to kilometers. There are 1.609 kilometers in a mile. 
Test your function with the following sequence of values using a loop: 1.0, 1.25, 1.5, 1.75, 2.0, ..., 3.0.

[source,java]
----
// Implement function: milesToKilometers
// Input: miles (double)
// output: kilometers (double)
----

* Write a function that computes the tip. 

[source,java]
----
// Implement function: computeTip
// Input: total cost (double)
// Input: tip percent (double)
// Output: double
----


* Write a function that computes the average of an array of numbers

[source,java]
----
// Implement function: computeAverage
// Input: values (array of double)
// Output: double
----

* Write a function that returns true if an array of double has a negative number on it.

[source,java]
----
// Implement function: containsNegative
// Input: values (array of double)
// Output: boolean
----

* Write a function that reverses the contents of an array. (Hint: create and return a new array in the function) 

[source,java]
----
// Implement function: reverseArray
// Input: values (array of double)
// Output: values (array of float)
----

4) Class practice.

* Implement a Movie class. Movie should contain the following data and methods

[source,java]
----
// Data

// Title (string)
// Duration in minutes (float)
// Year (integer)
// actors (array of String) 

// Methods

// Constructor 
// Input: Title (string)
// Input: Duration in minutes (float)
// Input: Year (integer)
// Input: actors (array of String) 

// Accessor for title
// Mutator for title 
----

* Test your Movie class. Create a Movie object for "The Shining" which was made in 1980, is 
2 hours and 26 minutes long, and stars Jack Nicholson and Shelley Duval. Create your object in `setup()`

6) A programmer has a bug in her code. She expected compute to return 4.0 but it's returning 3.0. What's wrong?

[source,java]
----
class Mystery {
  public static float compute(float a, float b, float c) {
    float tmp = a + b;
    return tmp - c;
    tmp += 1.0;
  }

  public static void main() {
    float result = compute(1.0, 4.0, 2.0);
    System.out.println(result);
  }
}
----

7) Consider the following program

[source,java]
----
class Mystery {
  public static int mystery(int[] values) {
    int total = 0;
    for (int i = 0; i < values.length; i++) {
      int value = values[i];
      if (values[i] < 0) {
        value = -value;
      }
      total += value;
      System.out.println("mystery: ", value, total);
    }
    return total;
  }

  public static void main(String[] args) {
    int[] values = {-1, 0, 1, 2, 3};
    System.out.println("Checkpoint 1:", values[2]);
    
    int result = mystery(values);
    System.out.println("Checkpoint 2: ", result);
  }
}
----

* What is the output of this program?
* What local variables are in scope in `setup()`? 
* What local variables are in scope in `mystery()`? 
* What is the return type of `mystery()`?

8) Consider the following program

[source,java]
----
class Mystery {
  public static String snaf(int a) {
    if (a < 5) {
      return "pop";
    }
    else {
      return "crackle";
    }
  }

  public static int fee(int q) {
    return -q;
  }

  public static int bar(int u, int v) {
    return -10*u + fee(v);
  }

  public static int foo(int x, int y) {
    return x*10 - fee(y);
  }

  public static void main(String[] args) {
    int a = -5;
    int b = 5;
    int c = 10;
    int d = foo(a, b);
    int e = bar(b, a);
    String result = snaf(d+e);
    System.out.println(result, d, e, d+e);
  }
}
----

* What console output is produced by this program?

10) Consider the following program

[source,java]
----
class Main {
  public static void main(String[] args) {
    
    Mystery m1 = new Mystery(4,1);
    Mystery m2 = new Mystery(1,1);
    
    int result1 = 0;
    int result2 = 0;
    result1 = m1.compute(2);
    result2 = m2.compute(2);
    System.out.println("BEFORE compute1: ", result1);
    System.out.println("BEFORE compute2: ", result2);
    
    m1.setA(3);
    m2.setB(3);
    
    result1 = m1.compute(2);
    result2 = m2.compute(2);
    System.out.println("AFTER compute1: ", result1);
    System.out.println("AFTER compute2: ", result2);
  }
}
----

where `Mystery` is defined as

[source,java]
----
class Mystery {

  int a = 0;
  int b = 0;
  
  Mystery(int x, int y) {
    a = x;
    b = y;
  }
  
  void setA(int x) {
    a = x;
  }
  
  void setB(int y) {
    b = y;
  }

  int compute(int factor) {
    return a + factor*b;
  }
}
----

* What is the console output of this program?
* What constructors are defined in this program?
* What member variables are defined in this program?
* What variables are in scope in Mystery's `compute` method? 
* What methods are defined in `Mystery`? 
* Implement an accessor method for the attribute (e.g. member variable) `a` in `Mystery`. 

